project:
  type: website

website:
  title: "Math Club at CUNY CSI"
  navbar:
    left:
      - href: pasteventss.qmd
        text: Events
      - about.qmd
      - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



