---
title: "Home"
---
Welcome to the Math Club at the College of Staten Island!

# Events!
## Upcoming Events!
| **Event Title**                                                                 | **Date**                               | **Description**                                                         | **Extra Information**                 |
|---------------------------------------------------------------------------------|----------------------------------------|-------------------------------------------------------------------------|---------------------------------------|
| [Pi Day Celebration!](assets/mathclubsocial0225)              | March 13th, 2025: 1S-214, 2:45      | It’s (almost) Pi Day! A time to honor the beauty of circles, the brilliance of 3.1415…, and the joy of discovery. Let’s celebrate with creativity, curiosity, and maybe even dessert! |             |

Here is a list of past events hosted by the Math Club at CUNY CSI. If you like what you see, come check us out!

## Spring 2024
| **Event Title**                                                                 | **Date**                               | **Description**                                                         | **Extra Information**                 |
|---------------------------------------------------------------------------------|----------------------------------------|-------------------------------------------------------------------------|---------------------------------------|
| [Love Algorithms: The Math of Modern Love](assets/OMExMathClub_flyer.pdf)              | February 12th, 2025: 1S-219, 3:00      | How does math shape dating algorithms? | [Short video explaining it all!](https://www.youtube.com/watch?v=uZLkhkCmwHg)             |
| [Math Club Social](assets/mathclubsocial0225)              | February 25th, 2025: 1S-214, 3:00      | Whether it’s numbers or nonsense, come chat with the Math Club at our relaxing afternoon social! |             |

## Fall 2024

| **Event Title**                                                                 | **Date**                               | **Description**                                                         | **Extra Information**                 |
|---------------------------------------------------------------------------------|----------------------------------------|-------------------------------------------------------------------------|---------------------------------------|
| [Student Research Presentations (Megan Trapanese)](assets/megan.pf)              | December 12th, 2024: 1S-219, 2:30      | Megan Trapanese (senior, MHC) presents her novel research on dimensonal reduction in the context of ensemble ocean modeling | [Check out her talk!](https://www.overleaf.com/read/qttczdghnddj#5a5cc9)             |
| [Topology & Cosmology, presented by Dr. Joseph Quinn!](assets/1126_mathclubposter.png)              | November 26th, 2024: 1S-219, 2:30      | A talk on 3-dimensional topology and its relationship to the shape of the physical universe. |              |
| [Math Club x Open Minds Exchange!](assets/OMExMathClub_flyer.pdf)              | October 24th, 2024: 1S-219, 2:30      | An intriguing and intellectual conversation with the Open Minds Exchange! | [Featured on CSI's LinkedIn page!](https://www.linkedin.com/posts/college-of-staten-island-city-university-of-new-york_wearecsi-activity-7256737820742938624-85hG?utm_source=share&utm_medium=member_desktop)             |
| [Beyond the Numbers: An Afternoon of Games!](assets/FallGames1.pdf)            | October 17th, 2024: 1S-214, 2:30      | Join the Math Club for an afternoon of fun, strategy, and board games!   |                   |
| [Math Club General Interest Meeting](assets/general_interest_flyer.pdf)        | September 19th, 2024: 1S-219, 2:30    | Come learn more about the Math Club and how you can get involved!        | [Slides Here!](assets/csimath_club_gim.pdf)     |
| [Simons Undergraduate Lecture: "On Buttons and Balls that Cannot Run Away", Prof. Bernd Kawhol of University of Cologne, Germany](assets/bernd.pdf) | September 10th, 2024: 1P-119 Lecture Hall, 2:30 | "In my talk, I shall survey some surprising geometrical facts and some of the history of their discovery. You will understand why some **British coins have corners** and what went wrong with a booster rocket at the 1986 disaster of the space shuttle Challenger" | Lecture followed by Q&A with the professor |

